### ISSUE TITLE
SSLError When Facting number

### ISSUE THREAD

**Issue by iromise** [ryosan-470/factordb-pycli#5]
Traceback (most recent call last):
  File "/usr/local/bin/factordb", line 11, in <module>
    load_entry_point('factordb-pycli==1.1.1', 'console_scripts', 'factordb')()
  File "/usr/local/lib/python2.7/dist-packages/factordb/cli.py", line 35, in main
    factordb.connect()
  File "/usr/local/lib/python2.7/dist-packages/factordb/factordb.py", line 18, in connect
    self.result = requests.get(ENDPOINT, params={"query": str(self.n)})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='factordb.com', port=443): Max retries exceeded with url: /api?query=9 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by ryosan-470** [comment]
Thanks for submitting an issue.  This issue happens because`https://factordb.com` SSL certificate is expired. Please submit a patch to modify this endpoint (`https://` to `http://`).

Thanks @iromise 

https://github.com/ryosan-470/factordb-pycli/blob/b5a2a6f3fc6fc3d5f8a6c8b03612070bff14e722/factordb/factordb.py#L18

**Comment by ryosan-470** [comment]
See #6

**Comment by iromise** [comment]
You have already fix it?

**Comment by ryosan-470** [comment]
Yeah. Please wait to merge and publish on pip.

**Comment by iromise** [comment]
ok, thanks.

**Comment by ryosan-470** [comment]
@iromise  Hi, I have published new release to fix this issue! Please upgrade this package on your environment. If you don't have any problem, please close this issue. Thanks a lot to contribute my project. 😂

**Comment by ryosan-470** [comment]
Release: https://github.com/ryosan-470/factordb-pycli/releases/tag/v1.2.0
PyPI: https://pypi.python.org/pypi/factordb-pycli

**Comment by iromise** [comment]
ok, there is no problem.
